/**
 * Chapter 3.1 — Neurons & Activations.
 *
 * One real neuron: weighted sum, bias, non-linearity. Every trace the player
 * compares against is produced by running that arithmetic over the same probe
 * points, so identifying an activation means reading its actual shape.
 */
import type { EngineRules, ScoreResult } from '@/types/game';
import { activate, type Activation } from '@/models/tinyNetTrainer';
import { scoreLevel } from './scoringEngine';
import { clamp, createRng, standardDeviation } from './shared';

export type NeuronMode = 'match-output' | 'identify-activation' | 'revive-dead-neuron';

export interface NeuronTuningConfig {
  mode: NeuronMode;
  activation: Activation;
  candidates?: Activation[];
  inputCount: number;
  weights: number[];
  bias: number;
  weightRange: [number, number];
  biasRange: [number, number];
  targetWeights?: number[];
  targetBias?: number;
  probePoints: number;
  seed: number;
  rounds?: number;
  minActiveFraction?: number;
}

export interface ActivationRound {
  /** The activation that actually produced this trace. */
  trueActivation: Activation;
  trace: number[];
  answer: Activation | null;
}

export interface NeuronTuningState {
  rules: EngineRules;
  status: 'idle' | 'active' | 'complete';
  actionCount: number;
  mode: NeuronMode;
  config: NeuronTuningConfig;
  weights: number[];
  bias: number;
  activation: Activation;
  /** Fixed sample points the neuron is evaluated over. */
  probes: number[][];
  targetOutputs: number[];
  rounds: ActivationRound[];
}

export type NeuronTuningAction =
  | { type: 'SET_WEIGHT'; index: number; value: number }
  | { type: 'SET_BIAS'; value: number }
  | { type: 'SET_ACTIVATION'; value: Activation }
  | { type: 'ANSWER_ACTIVATION'; roundIndex: number; value: Activation }
  | { type: 'RESET' }
  | { type: 'SUBMIT' };

/** Floor on the reference scale, so a flat target cannot make scoring explode. */
const MIN_REFERENCE_SCALE = 0.1;

function generateProbes(count: number, inputCount: number, seed: number): number[][] {
  const rng = createRng(seed);
  return Array.from({ length: count }, () =>
    Array.from({ length: inputCount }, () => rng() * 4 - 2)
  );
}

/** The neuron itself: weighted sum, bias, non-linearity. */
export function neuronOutput(
  weights: readonly number[],
  bias: number,
  activation: Activation,
  input: readonly number[]
): number {
  let sum = bias;
  for (let i = 0; i < weights.length; i++) sum += weights[i]! * (input[i] ?? 0);
  return activate(activation, sum);
}

export function preActivation(
  weights: readonly number[],
  bias: number,
  input: readonly number[]
): number {
  let sum = bias;
  for (let i = 0; i < weights.length; i++) sum += weights[i]! * (input[i] ?? 0);
  return sum;
}

export function initState(config: NeuronTuningConfig, rules: EngineRules): NeuronTuningState {
  const probes = generateProbes(config.probePoints, config.inputCount, config.seed);

  const targetOutputs =
    config.targetWeights && config.targetBias !== undefined
      ? probes.map((p) => neuronOutput(config.targetWeights!, config.targetBias!, config.activation, p))
      : [];

  // Each round's trace is generated by really running one candidate activation.
  const rounds: ActivationRound[] = [];
  if (config.mode === 'identify-activation' && config.candidates) {
    const rng = createRng(config.seed * 31 + 5);
    for (let r = 0; r < (config.rounds ?? 0); r++) {
      const trueActivation = config.candidates[Math.floor(rng() * config.candidates.length)]!;
      rounds.push({
        trueActivation,
        trace: probes.map((p) => neuronOutput(config.weights, config.bias, trueActivation, p)),
        answer: null,
      });
    }
  }

  return {
    rules,
    status: 'idle',
    actionCount: 0,
    mode: config.mode,
    config,
    weights: [...config.weights],
    bias: config.bias,
    activation: config.activation,
    probes,
    targetOutputs,
    rounds,
  };
}

export function applyAction(
  state: NeuronTuningState,
  action: NeuronTuningAction
): NeuronTuningState {
  const bump = (next: Partial<NeuronTuningState>): NeuronTuningState => ({
    ...state,
    ...next,
    status: 'active',
    actionCount: state.actionCount + 1,
  });

  switch (action.type) {
    case 'SET_WEIGHT': {
      if (action.index < 0 || action.index >= state.weights.length) return state;
      if (!Number.isFinite(action.value)) return state;
      const weights = [...state.weights];
      weights[action.index] = clamp(action.value, ...state.config.weightRange);
      return bump({ weights });
    }

    case 'SET_BIAS':
      if (!Number.isFinite(action.value)) return state;
      return bump({ bias: clamp(action.value, ...state.config.biasRange) });

    case 'SET_ACTIVATION':
      // The dead-neuron level is specifically about fixing it without swapping
      // the activation, so that escape hatch stays closed.
      if (state.mode === 'revive-dead-neuron') return state;
      return bump({ activation: action.value });

    case 'ANSWER_ACTIVATION': {
      const round = state.rounds[action.roundIndex];
      if (!round) return state;
      if (!state.config.candidates?.includes(action.value)) return state;
      const rounds = [...state.rounds];
      rounds[action.roundIndex] = { ...round, answer: action.value };
      return bump({ rounds });
    }

    case 'RESET':
      return initState(state.config, state.rules);

    case 'SUBMIT':
      return { ...state, status: 'complete', actionCount: state.actionCount + 1 };
  }
}

/** Current outputs across the probe set — the visualisation reads this. */
export function currentOutputs(state: NeuronTuningState): number[] {
  return state.probes.map((p) => neuronOutput(state.weights, state.bias, state.activation, p));
}

export function evaluate(state: NeuronTuningState): ScoreResult {
  switch (state.mode) {
    case 'match-output': {
      if (state.targetOutputs.length === 0) {
        return scoreLevel({ metric: 'outputMatchScore', value: 0, rules: state.rules });
      }
      const outputs = currentOutputs(state);
      const rmse = Math.sqrt(
        outputs.reduce((sum, o, i) => sum + (o - state.targetOutputs[i]!) ** 2, 0) / outputs.length
      );
      // Scale the error by how much the target actually varies, so matching a
      // near-constant target is not trivially rewarded.
      const scale = Math.max(standardDeviation(state.targetOutputs), MIN_REFERENCE_SCALE);
      return scoreLevel({
        metric: 'outputMatchScore',
        value: clamp(1 - rmse / scale, 0, 1),
        rules: state.rules,
        breakdown: { rmse, scale },
      });
    }

    case 'identify-activation': {
      const total = state.rounds.length;
      if (total === 0) {
        return scoreLevel({ metric: 'activationIdentificationAccuracy', value: 0, rules: state.rules });
      }
      const correct = state.rounds.filter((r) => r.answer === r.trueActivation).length;
      return scoreLevel({
        metric: 'activationIdentificationAccuracy',
        value: correct / total,
        rules: state.rules,
        breakdown: { correct, total },
      });
    }

    case 'revive-dead-neuron': {
      if (state.probes.length === 0) {
        return scoreLevel({ metric: 'activeFraction', value: 0, rules: state.rules });
      }
      // A ReLU unit is dead exactly when its pre-activation never clears zero,
      // so this is measured on the sum rather than the output.
      const active = state.probes.filter((p) => preActivation(state.weights, state.bias, p) > 0).length;
      return scoreLevel({
        metric: 'activeFraction',
        value: active / state.probes.length,
        rules: state.rules,
        breakdown: { active, total: state.probes.length },
      });
    }
  }
}
